### ISSUE TITLE
How to decide clusters to be merged or removed?

### ISSUE THREAD

**Issue by Xinrui0523** [eilslabs/ssam#8]
Hi, 

May I ask how do you decide which clusters to merge or remove in the de novo mode?
Theoretically, in the paper it's saying that 
> clusters showing a mismatch between panel 1 and panel 2, simultaneously having clear marker gene expression in panel 3 should be merged. 
> clusters with vectors outside the tissue region, representing image artifacts, centroids mapped to the artifacts, or no clear gene expression markers should be removed. 

Are they observed by eyes?
Take the osmFish SSp dataset in de novo mode as an example, 
the gene expression markers of cluster#2 is no more diverse than cluster#30, however, the #2
 is removed while #30 is merged into the cluster Pyramidal L2-3.

It seems the merged indices and removed indices pre-defined in the denovo_labels, where the 'N/A' stands for removing, and clusters with the same prefix (short name) are merged. Any domain knowledge required to facilitate this merging/removing process?

Thanks & regards
![diagplot_centroid_2](https://user-images.githubusercontent.com/13462883/68659403-2eee4800-0572-11ea-815e-32dab7627bfd.png)
![diagplot_centroid_30](https://user-images.githubusercontent.com/13462883/68659450-3c0b3700-0572-11ea-95e0-9af82ae6063b.png)

**Comment by pjb7687** [comment]
Hi,

It is not easy to determine whether some clusters have to be merged or removed. It is a manual step, and you would need some background knowledge of the cell types (e.g. marker genes) to do this. In my opinion it is generally a hard question for various datasets, not only SSAM - for example, it is also not easy to determine cell types in the clustering result of scRNA-seq data. Here one strength of SSAM is that you can additionally consider the spatial locations of the mapped centroid in the diagnostic plot, which can lead to the discovery of previously unknown cell types in tissue (e.g. Figure 6 in our preprint).

For clusters 2 and 30:
Cluster 2 is an easy case. It was removed because the centroid is mapped to the spurious areas in tissue. The KDE image of the highly expressed genes shows that the genes are exceptionally highly expressed within the area mapped in the second panel, we concluded that these are imaging artifact rather than the real gene expression in these areas. In the case of Cluster 30, it shows a mismatch between panel 1 and panel 2, therefore I merged it to the nearby cluster.

**Comment by Xinrui0523** [comment]
Thanks for your kind response.
