### ISSUE TITLE
Why is there an observable drop in the histogram of gene expression?

### ISSUE THREAD

**Issue by Xinrui0523** [eilslabs/ssam#9]
Hi, 

I tried out the SSAM on several other datasets, all getting an observable drop in the gene expression histogram, and two turning points for the L1-norm. So I just followed the paper to set thresholds. 
It seems not a coincidence. I'm quite curious but have no idea why. Do you have any comment? 

Thank you very much!
Regards

**Comment by pjb7687** [comment]
We revised our manuscript and added a bit more explanations regarding this based on what we have found during the revision. Shortly, we found that the location of the drop is near the height of a single Gaussian kernel; this is because the spots from the background noises (we think they are noises) are far apart from their closest nearest neighbor, and mostly they are single Gaussians. Since they disappear above the threshold, this is observed as a drop. Therefore, I think that setting a threshold at the drop is a good choice to remove background noises in many cases.
